// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Existing controllers
import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

// New controllers (jQuery migration)
import ContactFormController from "./contact_form_controller"
application.register("contact-form", ContactFormController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)
