
# lib/tasks/fix_nested_pictures.rake
namespace :images do
  desc "Fix nested/corrupted picture tags in content translations"
  task fix_nested_pictures: :environment do
    
    # We need an instance of the migration service to access helpers
    # Or we could just use ImagesHelper directly, but the service handles translation iteration well.
    # Actually, we need custom logic to UNWRAP first.
    
    include Pwb::ImagesHelper
    # Need ActionView helpers for the helper module to work if we used it directly
    include ActionView::Helpers::TagHelper
    include ActionView::Helpers::AssetTagHelper
    include ActionView::Helpers::UrlHelper
    include ActionView::Context
    
    puts "Starting repair of nested picture tags..."
    count = 0
    service = Pwb::ResponsiveContentMigrationService.new
    
    Pwb::Content.find_each do |content|
      changed = false
      updated_translations = content.translations.dup
      
      updated_translations.each do |locale, html_or_hash|
        next if html_or_hash.blank?
        
        # Handle Hash vs String structure
        if html_or_hash.is_a?(Hash)
          inner_content = html_or_hash['raw'] || html_or_hash['content']
          next unless inner_content.is_a?(String)
          
          repaired = repair_html(inner_content, service)
          
          if repaired != inner_content
            if html_or_hash['raw']
              html_or_hash['raw'] = repaired
            else
              html_or_hash['content'] = repaired
            end
            changed = true
          end
          
        elsif html_or_hash.is_a?(String)
          repaired = repair_html(html_or_hash, service)
          
          if repaired != html_or_hash
            updated_translations[locale] = repaired
            changed = true
          end
        end
      end
      
      if changed
        content.update_column(:translations, updated_translations)
        count += 1
        print "."
      end
    end
    
    puts "\nFinished. Repaired #{count} content records."
  end
  
  def repair_html(html, service)
    doc = Nokogiri::HTML::DocumentFragment.parse(html)
    has_changes = false
    
    # Strategy: Find any picture tag. 
    # If it looks like it was generated by our tool (has source/img children),
    # revert it to just the inner img tag.
    # Then re-run make_media_responsive on the clean HTML.
    
    # We iterate until no more picture tags are found to be safe? 
    # Or just find all, strip them.
    
    imgs_to_restore = []
    
    doc.css('picture').each do |pic|
      # Skip if we already marked this for removal (e.g. nested inside another we are removing)
      # But iterating doc.css('picture') handles nested ones in document order (pre-order usually).
      
      # We only want to strip pictures that we likely created or that are messed up.
      # Safest is to strip ALL pictures that wrap an img, and re-create them correctly.
      # This ensures consistency even for "good" ones if we changed the logic (e.g. sizes).
      
      img = pic.css('img').first
      if img
        # Clean the img attributes to ensure fresh generation
        img.remove_attribute('srcset')
        img.remove_attribute('sizes')
        # We can leave class, alt, style, etc.
        
        # Replace the picture with the img
        pic.replace(img)
        has_changes = true
      end
    end
    
    if has_changes
      # Now re-process with the service to apply correct, clean responsive tags
      return service.make_media_responsive(doc.to_html)
    end
    
    html
  end
end
