# frozen_string_literal: true

# == Schema Information
#
# Table name: pwb_widget_configs
# Database name: primary
#
#  id                :uuid             not null, primary key
#  active            :boolean          default(TRUE), not null
#  allowed_domains   :string           default([]), is an Array
#  clicks_count      :integer          default(0)
#  columns           :integer          default(3)
#  highlighted_only  :boolean          default(FALSE)
#  impressions_count :integer          default(0)
#  layout            :string           default("grid")
#  listing_type      :string
#  max_bedrooms      :integer
#  max_price_cents   :integer
#  max_properties    :integer          default(12)
#  min_bedrooms      :integer
#  min_price_cents   :integer
#  name              :string           not null
#  property_types    :string           default([]), is an Array
#  show_filters      :boolean          default(FALSE)
#  show_pagination   :boolean          default(TRUE)
#  show_search       :boolean          default(FALSE)
#  theme             :jsonb
#  visible_fields    :jsonb
#  widget_key        :string           not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  website_id        :bigint           not null
#
# Indexes
#
#  index_pwb_widget_configs_on_website_id             (website_id)
#  index_pwb_widget_configs_on_website_id_and_active  (website_id,active)
#  index_pwb_widget_configs_on_widget_key             (widget_key) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (website_id => pwb_websites.id)
#
FactoryBot.define do
  factory :pwb_widget_config, class: 'Pwb::WidgetConfig' do
    association :website, factory: :pwb_website
    sequence(:name) { |n| "Widget Config #{n}" }
    # widget_key is auto-generated by callback
    layout { 'grid' }
    columns { 3 }
    max_properties { 12 }
    active { true }
    show_search { false }
    show_filters { false }
    show_pagination { true }
    allowed_domains { [] }

    trait :list_layout do
      layout { 'list' }
    end

    trait :carousel_layout do
      layout { 'carousel' }
      columns { 4 }
    end

    trait :for_sale do
      listing_type { 'sale' }
    end

    trait :for_rent do
      listing_type { 'rent' }
    end

    trait :highlighted_only do
      highlighted_only { true }
    end

    trait :inactive do
      active { false }
    end

    trait :with_domain_restrictions do
      allowed_domains { ['example.com', '*.trusted.com'] }
    end

    trait :with_custom_theme do
      theme { { 'primary_color' => '#FF6B35', 'secondary_color' => '#004E89' } }
    end

    trait :with_price_filters do
      min_price_cents { 100_000_00 }
      max_price_cents { 500_000_00 }
    end

    trait :with_bedroom_filters do
      min_bedrooms { 2 }
      max_bedrooms { 4 }
    end

    trait :with_usage_stats do
      impressions_count { 1500 }
      clicks_count { 75 }
    end
  end
end
