# OMAK-style Rails 8 RuboCop Configuration
# Tailored for PropertyWebBuilder
#
# References:
# https://github.com/rails/rails/blob/main/.rubocop.yml
# https://github.com/rubocop/rubocop-rails

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'public/**/*'

# Rails 8 / OMAK preferences
# These settings aim for a balance between clean code and productivity

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

# Rails specific
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - e2e

Rails/Output:
  Enabled: true
  Exclude:
    - 'db/seeds.rb'
