# OMAK-style Rails 8 RuboCop Configuration
# Tailored for PropertyWebBuilder
#
# References:
# https://github.com/rails/rails/blob/main/.rubocop.yml
# https://github.com/rubocop/rubocop-rails

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'public/**/*'

# Rails 8 / OMAK preferences
# These settings aim for a balance between clean code and productivity

Style/Documentation:
  Enabled: false

# Disable string quote enforcement - too many changes for minimal benefit
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

# Disable - breaks classes that extend framework classes (e.g., ActiveStorage::Service)
Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/AbcSize:
  Max: 25

# Rails specific
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - e2e

Rails/Output:
  Enabled: true
  Exclude:
    - 'db/seeds.rb'

# Disable - falsely triggers on non-AR classes like Pwb::Theme
Rails/FindEach:
  Enabled: false

# Disable - can incorrectly modify case statements
Style/EmptyCaseCondition:
  Enabled: false

# Disable - can break method return values
Style/RedundantReturn:
  Enabled: false
