module ApiPublic
  module V1
    class SiteDetailsController < BaseController
      include ApiPublic::Cacheable
      include UrlLocalizationHelper

      def index
        locale = params[:locale] || I18n.default_locale
        I18n.locale = locale.to_sym

        website = Pwb::Current.website
        
        # Cache site details for 1 hour
        etag_data = [website.id, website.updated_at, I18n.locale]
        set_long_cache(max_age: 1.hour, etag_data: etag_data)
        return if performed?

        render json: build_site_details_response(website)
      end

      private

      def build_site_details_response(website)
        base_json = website.as_json
        
        # Add analytics config
        base_json.merge!(analytics: build_analytics_config(website))
        
        # Add requester info
        base_json.merge!(
          requester_locale: I18n.locale,
          requester_hostname: request.host
        )

        # Add SEO/Social fallbacks
        base_json.merge!(build_seo_defaults(website))

        # Add caching headers to body for client reference
        # (etag is generated by set_long_cache but we can recreate it for the body)
        base_json.merge!(
          last_modified: website.updated_at.iso8601,
          etag: "\"#{Digest::MD5.hexdigest(etag_data_string(website))}\"",
          cache_control: "public, max-age=3600"
        )

        base_json
      end

      def etag_data_string(website)
        "#{website.id}-#{website.updated_at}-#{I18n.locale}"
      end

      def build_seo_defaults(website)
        title = website.company_display_name.presence || "Home"
        description = website.default_meta_description.presence || "Find your dream property"
        site_name = website.company_display_name.presence || website.agency&.display_name.presence || "Property Website"
        
        {
          title: title,
          meta_description: description,
          meta_keywords: nil, # Site-wide default usually nil unless configured
          
          og: {
            "og:title" => title,
            "og:description" => description,
            "og:type" => "website",
            "og:url" => root_url_for_locale,
            "og:site_name" => site_name,
            "og:image" => website.logo_url.presence
          }.compact,

          twitter: {
            "twitter:card" => "summary_large_image",
            "twitter:title" => title,
            "twitter:description" => description,
            "twitter:image" => website.logo_url.presence
          }.compact,

          json_ld: {
            "@context" => "https://schema.org",
            "@type" => "WebSite",
            "name" => site_name,
            "url" => root_url_for_locale,
            "inLanguage" => I18n.locale.to_s,
            "datePublished" => website.created_at&.to_date&.iso8601,
            "dateModified" => website.updated_at&.to_date&.iso8601,
            "publisher" => {
              "@type" => "Organization",
              "name" => site_name,
              "logo" => (website.logo_url.present? ? { "@type" => "ImageObject", "url" => website.logo_url } : nil)
            }.compact
          }.compact
        }
      end

      def root_url_for_locale
        # If default locale, use root, else use /locale
        default_locale = Pwb::Current.website&.default_client_locale&.to_s || "en"
        path = I18n.locale.to_s == default_locale ? "/" : "/#{I18n.locale}/"
        "#{request.protocol}#{request.host_with_port}#{path}"
      end

      def build_analytics_config(website)
        config = {}

        # Posthog
        if website.respond_to?(:posthog_api_key) && website.posthog_api_key.present?
          config[:posthog_key] = website.posthog_api_key
          config[:posthog_host] = website.respond_to?(:posthog_host) ? website.posthog_host : "https://app.posthog.com"
        end

        # Google Analytics 4
        config[:ga4_id] = website.ga4_measurement_id if website.respond_to?(:ga4_measurement_id) && website.ga4_measurement_id.present?

        # Google Tag Manager
        config[:gtm_id] = website.gtm_container_id if website.respond_to?(:gtm_container_id) && website.gtm_container_id.present?

        config.presence
      end
    end
  end
end
